version: '3.7'
services:
    nginx:
        image: nginx:latest
        container_name: nginx
        hostname: "nginx"
        restart: unless-stopped
        working_dir: /app
        volumes:
            - ./:/app
            - ./config/docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - "8000:8000"
        depends_on:
            - app
        links:
            - "app:php"
            - "app:php-fpm"
        networks:
            - default
    app:
        build:
            context: .
        image: "mts-test-app"
        hostname: "app"
        container_name: app
        restart: unless-stopped
        working_dir: /app
        labels:
            com.symfony.server.service-ignore: true
        volumes:
            -   type: bind
                source: ./
                target: /app_source
                read_only: true
        user: "www-data:www-data"
        depends_on:
            - mysql
        links:
            - "mysql:db"
        networks:
            - default
    mysql:
        image: mysql:latest
        container_name: mysql
        hostname: "mysql"
        restart: unless-stopped
        command:
            - '--character-set-server=utf8mb4'
            - '--default-authentication-plugin=mysql_native_password'
            - '--secure-file-priv=NULL'
            - '--innodb_use_native_aio=0'
            - '--skip-name-resolve=1'
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: mts_test
            MYSQL_USER: mts_test
            MYSQL_PASSWORD: Mts_Test!
        cap_add:
            - SYS_NICE
        volumes:
            - mysql-data:/var/lib/mysql
            - ./config/docker/mysql/my.cnf:/etc/mysql/my.cnf
        ports:
            - "3306:3306"
        labels:
            com.symfony.server.service-prefix: 'DATABASE'
        networks:
            - default
volumes:
    mysql-data:
        driver: local
networks:
    default:
        driver: bridge
